export const languages = {
  aa: { order:  1, iso_639_1: 'aa', en: 'Afar',        label: 'Afar' },
  ab: { order:  2, iso_639_1: 'ab', en: 'Abkhazian',   label: 'Аҧсуа' },
  ae: { order:  3, iso_639_1: 'ae', en: 'Avestan',     label: 'Avesta' },
  af: { order:  4, iso_639_1: 'af', en: 'Afrikaans',   label: 'Afrikaans' },
  ak: { order:  5, iso_639_1: 'ak', en: 'Akan',        label: 'Akana' },
  am: { order:  6, iso_639_1: 'am', en: 'Amharic',     label: 'አማርኛ' },
  an: { order:  7, iso_639_1: 'an', en: 'Aragonese',   label: 'Aragonés' },
  ar: { order:  8, iso_639_1: 'ar', en: 'Arabic',      label: 'العربية' },
  as: { order:  9, iso_639_1: 'as', en: 'Assamese',    label: 'অসমীয়া' },
  av: { order: 10, iso_639_1: 'av', en: 'Avaric',      label: 'Авар' },
  ay: { order: 11, iso_639_1: 'ay', en: 'Aymara',      label: 'Aymar' },
  az: { order: 12, iso_639_1: 'az', en: 'Azerbaijani', label: 'Azərbaycanca' },
  ba: { order: 13, iso_639_1: 'ba', en: 'Bashkir',     label: 'Bashkort' },
  be: { order: 14, iso_639_1: 'be', en: 'Belarusian',  label: 'Беларуская' },
  bg: { order: 15, iso_639_1: 'bg', en: 'Bulgarian',   label: 'Български' },
  bi: { order: 16, iso_639_1: 'bi', en: 'Bislama', label: 'Bislama' },
  bm: { order: 17, iso_639_1: 'bm', en: 'Bambara', label: 'Bamanankan' },
  bn: { order: 18, iso_639_1: 'bn', en: 'Bengali', label: 'বাংলা' },
  bo: { order: 19, iso_639_1: 'bo', en: 'Tibetan', label: 'བོད་ཡིག' },
  br: { order: 20, iso_639_1: 'br', en: 'Breton', label: 'Brezhoneg' },
  bs: { order: 21, iso_639_1: 'bs', en: 'Bosnian', label: 'Bosanski' },
  ca: { order: 22, iso_639_1: 'ca', en: 'Catalan', label: 'Català' },
  ce: { order: 23, iso_639_1: 'ce', en: 'Chechen', label: 'Нохчийн' },
  ch: { order: 24, iso_639_1: 'ch', en: 'Chamorro', label: 'Chamoru' },
  co: { order: 25, iso_639_1: 'co', en: 'Corsican', label: 'Corsu' },
  cr: { order: 26, iso_639_1: 'cr', en: 'Cree', label: 'Nehiyawewin' },
  cs: { order: 27, iso_639_1: 'cs', en: 'Czech', label: 'Čeština' },
  cu: { order: 28, iso_639_1: 'cu', en: 'Church Slavic', label: 'Словѣньскъ' },
  cv: { order: 29, iso_639_1: 'cv', en: 'Chuvash', label: 'Чӑваш' },
  cy: { order: 30, iso_639_1: 'cy', en: 'Welsh', label: 'Cymraeg' },
  da: { order: 31, iso_639_1: 'da', en: 'Danish', label: 'Dansk' },
  de: { order: 32, iso_639_1: 'de', en: 'German', label: 'Deutsch' },
  dv: { order: 33, iso_639_1: 'dv', en: 'Divehi', label: 'ދިވެހިބަސް' },
  dz: { order: 34, iso_639_1: 'dz', en: 'Dzongkha', label: 'རྫོང་ཁ' },
  ee: { order: 35, iso_639_1: 'ee', en: 'Ewe', label: 'Eʋegbe' },
  el: { order: 36, iso_639_1: 'el', en: 'Greek', label: 'Ελληνικά' },
  en: { order: 37, iso_639_1: 'en', en: 'English', label: 'English' },
  eo: { order: 38, iso_639_1: 'eo', en: 'Esperanto', label: 'Esperanto' },
  es: { order: 39, iso_639_1: 'es', en: 'Spanish', label: 'Español' },
  et: { order: 40, iso_639_1: 'et', en: 'Estonian', label: 'Eesti' },
  eu: { order: 41, iso_639_1: 'eu', en: 'Basque', label: 'Euskara' },
  fa: { order: 42, iso_639_1: 'fa', en: 'Persian', label: 'فارسی' },
  ff: { order: 43, iso_639_1: 'ff', en: 'Fulah', label: 'Fulfulde' },
  fi: { order: 44, iso_639_1: 'fi', en: 'Finnish', label: 'Suomi' },
  fj: { order: 45, iso_639_1: 'fj', en: 'Fijian', label: 'Na Vosa Vakaviti' },
  fo: { order: 46, iso_639_1: 'fo', en: 'Faroese', label: 'Føroyskt' },
  fr: { order: 47, iso_639_1: 'fr', en: 'French', label: 'Français' },
  fy: { order: 48, iso_639_1: 'fy', en: 'Western Frisian', label: 'Frysk' },
  ga: { order: 49, iso_639_1: 'ga', en: 'Irish', label: 'Gaeilge' },
  gd: { order: 50, iso_639_1: 'gd', en: 'Gaelic', label: 'Gàidhlig' },
  gl: { order: 51, iso_639_1: 'gl', en: 'Galician', label: 'Galego' },
  gn: { order: 52, iso_639_1: 'gn', en: 'Guarani', label: 'Avañe\'ẽ' },
  gu: { order: 53, iso_639_1: 'gu', en: 'Gujarati', label: 'ગુજરાતી' },
  gv: { order: 54, iso_639_1: 'gv', en: 'Manx', label: 'Gaelg' },
  ha: { order: 55, iso_639_1: 'ha', en: 'Hausa', label: 'هَوُسَ' },
  he: { order: 56, iso_639_1: 'he', en: 'Hebrew', label: 'עברית' },
  hi: { order: 57, iso_639_1: 'hi', en: 'Hindi', label: 'हिन्दी' },
  ho: { order: 58, iso_639_1: 'ho', en: 'Hiri Motu', label: 'Hiri Motu' },
  hr: { order: 59, iso_639_1: 'hr', en: 'Croatian', label: 'Hrvatski' },
  ht: { order: 60, iso_639_1: 'ht', en: 'Haitian', label: 'Kreyòl ayisyen' },
  hu: { order: 61, iso_639_1: 'hu', en: 'Hungarian', label: 'Magyar' },
  hy: { order: 62, iso_639_1: 'hy', en: 'Armenian', label: 'Հայերեն' },
  hz: { order: 63, iso_639_1: 'hz', en: 'Herero', label: 'Otjiherero' },
  ia: { order: 64, iso_639_1: 'ia', en: 'Interlingua', label: 'Interlingua' },
  id: { order: 65, iso_639_1: 'id', en: 'Indonesian', label: 'Bahasa Indonesia' },
  ie: { order: 66, iso_639_1: 'ie', en: 'Interlingue', label: 'Interlingue' },
  ig: { order: 67, iso_639_1: 'ig', en: 'Igbo', label: 'Asụsụ Igbo' },
  ii: { order: 68, iso_639_1: 'ii', en: 'Sichuan Yi', label: 'ꆈꌠ꒿' },
  ik: { order: 69, iso_639_1: 'ik', en: 'Inupiaq', label: 'Iñupiaq' },
  io: { order: 70, iso_639_1: 'io', en: 'Ido', label: 'Ido' },
  is: { order: 71, iso_639_1: 'is', en: 'Icelandic', label: 'Íslenska' },
  it: { order: 72, iso_639_1: 'it', en: 'Italian', label: 'Italiano' },
  iu: { order: 73, iso_639_1: 'iu', en: 'Inuktitut', label: 'ᐃᓄᒃᑎᑐᑦ' },
  ja: { order: 74, iso_639_1: 'ja', en: 'Japanese', label: '日本語' },
  jv: { order: 75, iso_639_1: 'jv', en: 'Javanese', label: 'Basa Jawa' },
  ka: { order: 76, iso_639_1: 'ka', en: 'Georgian', label: 'ქართული' },
  kg: { order: 77, iso_639_1: 'kg', en: 'Kongo', label: 'Kikongo' },
  ki: { order: 78, iso_639_1: 'ki', en: 'Kikuyu', label: 'Gĩkũyũ' },
  kj: { order: 79, iso_639_1: 'kj', en: 'Kuanyama', label: 'Kuanyama' },
  kk: { order: 80, iso_639_1: 'kk', en: 'Kazakh', label: 'Қазақша' },
  kl: { order: 81, iso_639_1: 'kl', en: 'Kalaallisut', label: 'Kalaallisut' },
  km: { order: 82, iso_639_1: 'km', en: 'Khmer', label: 'ភាសាខ្មဲរ' },
  kn: { order: 83, iso_639_1: 'kn', en: 'Kannada', label: 'ಕನ್ನಡ' },
  ko: { order: 84, iso_639_1: 'ko', en: 'Korean', label: '한국어' },
  kr: { order: 85, iso_639_1: 'kr', en: 'Kanuri', label: 'Kanuri' },
  ks: { order: 86, iso_639_1: 'ks', en: 'Kashmiri', label: 'कश्मीरी' },
  ku: { order: 87, iso_639_1: 'ku', en: 'Kurdish', label: 'Kurdî' },
  kv: { order: 88, iso_639_1: 'kv', en: 'Komi', label: 'Коми' },
  kw: { order: 89, iso_639_1: 'kw', en: 'Cornish', label: 'Kernewek' },
  ky: { order: 90, iso_639_1: 'ky', en: 'Kirghiz', label: 'Кыргызча' },
  la: { order: 91, iso_639_1: 'la', en: 'Latin', label: 'Latina' },
  lb: { order: 92, iso_639_1: 'lb', en: 'Luxembourgish', label: 'Lëtzebuergesch' },
  lg: { order: 93, iso_639_1: 'lg', en: 'Ganda', label: 'Luganda' },
  li: { order: 94, iso_639_1: 'li', en: 'Limburgish', label: 'Limburgs' },
  ln: { order: 95, iso_639_1: 'ln', en: 'Lingala', label: 'Lingála' },
  lo: { order: 96, iso_639_1: 'lo', en: 'Lao', label: 'ພາສາລາວ' },
  lt: { order: 97, iso_639_1: 'lt', en: 'Lithuanian', label: 'Lietuvių' },
  lu: { order: 98, iso_639_1: 'lu', en: 'Luba-Katanga', label: 'Tshiluba' },
  lv: { order: 99, iso_639_1: 'lv', en: 'Latvian', label: 'Latviešu' },
  mg: { order: 100, iso_639_1: 'mg', en: 'Malagasy', label: 'Malagasy' },
  mh: { order: 101, iso_639_1: 'mh', en: 'Marshallese', label: 'Kajin M̧ajeļ' },
  mi: { order: 102, iso_639_1: 'mi', en: 'Maori', label: 'Te Reo Māori' },
  mk: { order: 103, iso_639_1: 'mk', en: 'Macedonian', label: 'Македонски' },
  ml: { order: 104, iso_639_1: 'ml', en: 'Malayalam', label: 'മലയാളം' },
  mn: { order: 105, iso_639_1: 'mn', en: 'Mongolian', label: 'Монгол' },
  mr: { order: 106, iso_639_1: 'mr', en: 'Marathi', label: 'मराठी' },
  ms: { order: 107, iso_639_1: 'ms', en: 'Malay', label: 'Bahasa Melayu' },
  mt: { order: 108, iso_639_1: 'mt', en: 'Maltese', label: 'Malti' },
  my: { order: 109, iso_639_1: 'my', en: 'Burmese', label: 'ဗမာစာ' },
  na: { order: 110, iso_639_1: 'na', en: 'Nauru', label: 'Ekakairũ Naoero' },
  nb: { order: 111, iso_639_1: 'nb', en: 'Bokmål, Norwegian', label: 'Norsk bokmål' },
  nd: { order: 112, iso_639_1: 'nd', en: 'North Ndebele', label: 'isiNdebele' },
  ne: { order: 113, iso_639_1: 'ne', en: 'Nepali', label: 'नेपाली' },
  ng: { order: 114, iso_639_1: 'ng', en: 'Ndonga', label: 'Owambo' },
  nl: { order: 115, iso_639_1: 'nl', en: 'Dutch', label: 'Nederlands' },
  nn: { order: 116, iso_639_1: 'nn', en: 'Norwegian Nynorsk', label: 'Norsk nynorsk' },
  no: { order: 117, iso_639_1: 'no', en: 'Norwegian', label: 'Norsk' },
  nr: { order: 118, iso_639_1: 'nr', en: 'South Ndebele', label: 'isiNdebele' },
  nv: { order: 119, iso_639_1: 'nv', en: 'Navajo', label: 'Diné bizaad' },
  ny: { order: 120, iso_639_1: 'ny', en: 'Chichewa', label: 'Chi-Chewa' },
  oc: { order: 121, iso_639_1: 'oc', en: 'Occitan', label: 'Occitan' },
  oj: { order: 122, iso_639_1: 'oj', en: 'Ojibwa', label: 'ᐊᓂᔑᓈᐯᒧ win' },
  om: { order: 123, iso_639_1: 'om', en: 'Oromo', label: 'Afaan Oromoo' },
  or: { order: 124, iso_639_1: 'or', en: 'Oriya', label: 'ଓଡ଼ିଆ' },
  os: { order: 125, iso_639_1: 'os', en: 'Ossetian', label: 'Ирон' },
  pa: { order: 126, iso_639_1: 'pa', en: 'Panjabi', label: 'ਪੰਜਾਬੀ' },
  pi: { order: 127, iso_639_1: 'pi', en: 'Pali', label: 'पाळि' },
  pl: { order: 128, iso_639_1: 'pl', en: 'Polish', label: 'Polski' },
  ps: { order: 129, iso_639_1: 'ps', en: 'Pashto', label: 'پښتو' },
  pt: { order: 130, iso_639_1: 'pt', en: 'Portuguese', label: 'Português' },
  qu: { order: 131, iso_639_1: 'qu', en: 'Quechua', label: 'Runa Simi' },
  rm: { order: 132, iso_639_1: 'rm', en: 'Romansh', label: 'Rumantsch' },
  rn: { order: 133, iso_639_1: 'rn', en: 'Rundi', label: 'Kirundi' },
  ro: { order: 134, iso_639_1: 'ro', en: 'Romanian', label: 'Română' },
  ru: { order: 135, iso_639_1: 'ru', en: 'Russian', label: 'Русский' },
  rw: { order: 136, iso_639_1: 'rw', en: 'Kinyarwanda', label: 'Ikinyarwanda' },
  sa: { order: 137, iso_639_1: 'sa', en: 'Sanskrit', label: 'संस्कृतम्' },
  sc: { order: 138, iso_639_1: 'sc', en: 'Sardinian', label: 'Sardu' },
  sd: { order: 139, iso_639_1: 'sd', en: 'Sindhi', label: 'سنڌي' },
  se: { order: 140, iso_639_1: 'se', en: 'Northern Sami', label: 'Davvisámegiella' },
  sg: { order: 141, iso_639_1: 'sg', en: 'Sango', label: 'Yângâ tî Sängö' },
  si: { order: 142, iso_639_1: 'si', en: 'Sinhala', label: 'සිංහල' },
  sk: { order: 143, iso_639_1: 'sk', en: 'Slovak', label: 'Slovenčina' },
  sl: { order: 144, iso_639_1: 'sl', en: 'Slovenian', label: 'Slovenščina' },
  sm: { order: 145, iso_639_1: 'sm', en: 'Samoan', label: 'Gagana fa\'a Samoa' },
  sn: { order: 146, iso_639_1: 'sn', en: 'Shona', label: 'chiShona' },
  so: { order: 147, iso_639_1: 'so', en: 'Somali', label: 'Soomaaliga' },
  sq: { order: 148, iso_639_1: 'sq', en: 'Albanian', label: 'Shqip' },
  sr: { order: 149, iso_639_1: 'sr', en: 'Serbian', label: 'Српски' },
  ss: { order: 150, iso_639_1: 'ss', en: 'Swati', label: 'SiSwati' },
  st: { order: 151, iso_639_1: 'st', en: 'Southern Sotho', label: 'Sesotho' },
  su: { order: 152, iso_639_1: 'su', en: 'Sundanese', label: 'Basa Sunda' },
  sv: { order: 153, iso_639_1: 'sv', en: 'Swedish', label: 'Svenska' },
  sw: { order: 154, iso_639_1: 'sw', en: 'Swahili', label: 'Kiswahili' },
  ta: { order: 155, iso_639_1: 'ta', en: 'Tamil', label: 'தமிழ்' },
  te: { order: 156, iso_639_1: 'te', en: 'Telugu', label: 'తెలుగు' },
  tg: { order: 157, iso_639_1: 'tg', en: 'Tajik', label: 'Тоҷикӣ' },
  th: { order: 158, iso_639_1: 'th', en: 'Thai', label: 'ไทย' },
  ti: { order: 159, iso_639_1: 'ti', en: 'Tigrinya', label: 'ትግርኛ' },
  tk: { order: 160, iso_639_1: 'tk', en: 'Turkmen', label: 'Türkmençe' },
  tl: { order: 161, iso_639_1: 'tl', en: 'Tagalog', label: 'Tagalog' },
  tn: { order: 162, iso_639_1: 'tn', en: 'Tswana', label: 'Setswana' },
  to: { order: 163, iso_639_1: 'to', en: 'Tonga', label: 'Faka Tonga' },
  tr: { order: 164, iso_639_1: 'tr', en: 'Turkish', label: 'Türkçe' },
  ts: { order: 165, iso_639_1: 'ts', en: 'Tsonga', label: 'Xitsonga' },
  tt: { order: 166, iso_639_1: 'tt', en: 'Tatar', label: 'Татарча' },
  tw: { order: 167, iso_639_1: 'tw', en: 'Twi', label: 'Twi' },
  ty: { order: 168, iso_639_1: 'ty', en: 'Tahitian', label: 'Reo Māohi' },
  ug: { order: 169, iso_639_1: 'ug', en: 'Uighur', label: 'ئۇيغۇرچە' },
  uk: { order: 170, iso_639_1: 'uk', en: 'Ukrainian', label: 'Українська' },
  ur: { order: 171, iso_639_1: 'ur', en: 'Urdu', label: 'اردو' },
  uz: { order: 172, iso_639_1: 'uz', en: 'Uzbek', label: 'Oʻzbekcha' },
  ve: { order: 173, iso_639_1: 've', en: 'Venda', label: 'Tshivenda' },
  vi: { order: 174, iso_639_1: 'vi', en: 'Vietnamese', label: 'Tiếng Việt' },
  vo: { order: 175, iso_639_1: 'vo', en: 'Volapük', label: 'Volapük' },
  wa: { order: 176, iso_639_1: 'wa', en: 'Walloon', label: 'Walon' },
  wo: { order: 177, iso_639_1: 'wo', en: 'Wolof', label: 'Wollof' },
  xh: { order: 178, iso_639_1: 'xh', en: 'Xhosa', label: 'isiXhosa' },
  yi: { order: 179, iso_639_1: 'yi', en: 'Yiddish', label: 'ייִדיש' },
  yo: { order: 180, iso_639_1: 'yo', en: 'Yoruba', label: 'Yorùbá' },
  za: { order: 181, iso_639_1: 'za', en: 'Zhuang', label: 'Saɯ cueŋƅ' },
  zh: { order: 182, iso_639_1: 'zh', en: 'Chinese', label: '中文' },
  zu: { order: 183, iso_639_1: 'zu', en: 'Zulu', label: 'isiZulu' }
};