title: Jindřich Ochmann
logo: /assets/img/20250712_030.jpg
description: Software Engineer
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

nav:
  - title: Projekty
    url: /projects
  - title: Kontakt
    url: /contacts
  - title: Tutorialy
    url: /tutorials
    sublinks:
      - title: Git
        url: /tutorials/git/git
        sublinks:
          - title: GitHub
            url: /tutorials/git/github
            sublinks:
              - title: Pages
                url: /tutorials/git/github/pages
      - title: Markdown
        url: /tutorials/markdown/markdown
      - title: C/C++
        url: /tutorials/c/c
      #- title: C#
      #  url: /tutorials/csharp
      #- title: Java
      #  url: /tutorials/java
      #- title: JavaScript
      #  url: /tutorials/javascript
      #- title: PHP
      #  url: /tutorials/php
      #- title: Python
      #  url: /tutorials/python
      #- title: SQL
      #  url: /tutorials/sql
      - title: CheatSheet
        url: /tutorials/cheatsheet
